version: '2'

services:
  nginx-proxy:
    image: ghcr.io/nginx-proxy/nginx-proxy:1.0.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    restart: unless-stopped

  acme-companion:
    image: ghcr.io/nginx-proxy/acme-companion:2.2.3
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=contact@aimedlabs.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    restart: unless-stopped

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
