version: '3'

services:
  kms:
    image: ghcr.io/aimed-labs/github-runner-kms:latest
    restart: always
    environment:
      PAT_aimed-labs: ${PAT}

  runner:
    image: ghcr.io/aimed-labs/github-runner-amd64:focal-2.299.1
    restart: always
    environment:
      RUNNER_REGISTER_TO: 'aimed-labs'
      RUNNER_LABELS: 'docker,aimed-labs,aimed-labs-infra'
      ADDITIONAL_FLAGS: '--ephemeral'
      KMS_SERVER_ADDR: 'http://kms:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kms
