name: Build Runner Image

on:
  workflow_dispatch:
    inputs:
      github-runner-version:
        description: 'Version on github runner(in https://github.com/actions/runner), e.g: 2.290.0'
        required: true
        default: '2.299.1'

jobs:
  build-amd64-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./github-runner
    env:
      PAT: ${{ secrets.SHAKTIMAN_PAT }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: aimed-labs
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-amd64-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-amd64

      - name: Build and push AMD64 Version
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: GITHUB_RUNNER_VERSION=${{ github.event.inputs.github-runner-version }}
          tags: |
            ghcr.io/aimed-labs/github-runner-amd64:focal-${{ github.event.inputs.github-runner-version }}

          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
